/*
    ChibiOS - Copyright (C) 2006..2020 Giovanni Di Sirio
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
 
        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
 
#ifndef MCUCONF_H
#define MCUCONF_H
 
#define SAME54_MCUCONF
 
#define SAM_CPUDIV 1
 
#define SAM_RTC_GCLK_SRC_ID 8
#define SAM_RTC_DIV 6
 
#define SAM_ADC_GCLK_SRC_ID 0
#define SAM_SERCOM0_GCLK_SRC_ID 0
#define SAM_SERCOM1_GCLK_SRC_ID 0
#define SAM_SERCOM2_GCLK_SRC_ID 7
#define SAM_SERCOM3_GCLK_SRC_ID 0
#define SAM_SERCOM4_GCLK_SRC_ID 0
#define SAM_SERCOM5_GCLK_SRC_ID 0
#define SAM_SERCOM6_GCLK_SRC_ID 9
#define SAM_SERCOM7_GCLK_SRC_ID 7
#define SAM_USB_GCLK_SRC_ID 9
#define SAM_TCC0_TCC1_GCLK_SRC_ID 0
#define SAM_TCC2_TC3_GCLK_SRC_ID 0
 
/********************* XOSC *******************/
 
#define SAM_XOSC1_FREQ 12000000UL
#define SAM_XOSC0_ENABLED FALSE
#define SAM_XOSC1_ENABLED TRUE
#define SAM_FDPLL0_INPUT_SRC SAM_DPLL_INPUT_SRC_XOSC1
#define SAM_FDPLL1_INPUT_SRC SAM_DPLL_INPUT_SRC_XOSC1
 
#define SAM_FDPLL0_ENABLED TRUE
#define SAM_FDPLL1_ENABLED TRUE
 
#define SAM_FDPLL0_DIV 5
#define SAM_FDPLL0_LDR 119
#define SAM_FDPLL0_LDFRAC 0
 
#define SAM_FDPLL1_DIV 5
#define SAM_FDPLL1_LDR 95
#define SAM_FDPLL1_LDFRAC 0
 
/******************** GENCLK *******************/
#define SAM_GCLK0_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK0_FREQ 120000000UL
 
#define SAM_GCLK1_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK1_FREQ 60000000UL
#define SAM_GCLK1_ENABLE FALSE
 
#define SAM_GCLK2_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK2_FREQ 60000000UL
#define SAM_GCLK2_ENABLE FALSE
 
#define SAM_GCLK3_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK3_FREQ 1000000UL
#define SAM_GCLK3_ENABLE FALSE
 
#define SAM_GCLK4_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK4_FREQ 1000000UL
#define SAM_GCLK4_ENABLE FALSE
 
#define SAM_GCLK5_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK5_FREQ 1000000UL
#define SAM_GCLK5_ENABLE FALSE
 
#define SAM_GCLK6_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK6_FREQ 1000000UL
#define SAM_GCLK6_ENABLE FALSE
 
#define SAM_GCLK7_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK7_FREQ 10000000UL
#define SAM_GCLK7_ENABLE TRUE
 
#define SAM_GCLK8_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK8_FREQ 640000UL
#define SAM_GCLK8_ENABLE TRUE
 
#define SAM_GCLK9_SRC GCLK_GENCTRL_SRC_DPLL1
#define SAM_GCLK9_FREQ 48000000UL
#define SAM_GCLK9_ENABLE TRUE
 
#define SAM_GCLK10_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK10_FREQ 1000000UL
#define SAM_GCLK10_ENABLE FALSE
 
#define SAM_GCLK11_SRC GCLK_GENCTRL_SRC_DPLL0
#define SAM_GCLK11_FREQ 1000000UL
#define SAM_GCLK11_ENABLE FALSE
 
/***********************************************/
 
#define SAM_DMAC_IRQ_PRIORITY 4
#define SAM_QSPI_IRQ_PRIORITY 5
#define SAM_ADC_IRQ_PRIORITY 6
 
#define SAM_EIC_EXTI0_IRQ_PRIORITY 6
#define SAM_EIC_EXTI1_IRQ_PRIORITY 6
#define SAM_EIC_EXTI2_IRQ_PRIORITY 6
#define SAM_EIC_EXTI3_IRQ_PRIORITY 6
#define SAM_EIC_EXTI4_IRQ_PRIORITY 6
#define SAM_EIC_EXTI5_IRQ_PRIORITY 6
#define SAM_EIC_EXTI6_IRQ_PRIORITY 6
#define SAM_EIC_EXTI7_IRQ_PRIORITY 6
#define SAM_EIC_EXTI8_IRQ_PRIORITY 6
#define SAM_EIC_EXTI9_IRQ_PRIORITY 6
#define SAM_EIC_EXTI10_IRQ_PRIORITY 6
#define SAM_EIC_EXTI11_IRQ_PRIORITY 6
#define SAM_EIC_EXTI12_IRQ_PRIORITY 6
#define SAM_EIC_EXTI13_IRQ_PRIORITY 6
#define SAM_EIC_EXTI14_IRQ_PRIORITY 6
#define SAM_EIC_EXTI15_IRQ_PRIORITY 6
 
#define SAM_RTC_IRQ_PRIORITY 6
 
#define SAM_SERCOM0_IRQ_PRIORITY 5
#define SAM_SERCOM1_IRQ_PRIORITY 5
#define SAM_SERCOM2_IRQ_PRIORITY 5
#define SAM_SERCOM3_IRQ_PRIORITY 5
#define SAM_SERCOM4_IRQ_PRIORITY 5
#define SAM_SERCOM5_IRQ_PRIORITY 5
#define SAM_SERCOM6_IRQ_PRIORITY 5
#define SAM_SERCOM7_IRQ_PRIORITY 5
#define SAM_TCC0_IRQ_PRIORITY 6
#define SAM_TC3_IRQ_PRIORITY 6
 
#define SAM_ADC_USE_ADC1 FALSE
 
#define SAM_SIO_USE_SERCOM0 FALSE
#define SAM_SPI_USE_SERCOM0 FALSE
#define SAM_I2C_USE_SERCOM0 FALSE
 
#define SAM_SIO_USE_SERCOM1 FALSE
#define SAM_SPI_USE_SERCOM1 FALSE
#define SAM_I2C_USE_SERCOM1 FALSE
 
#define SAM_SIO_USE_SERCOM2 TRUE
#define SAM_SPI_USE_SERCOM2 FALSE
#define SAM_I2C_USE_SERCOM2 FALSE
 
#define SAM_SIO_USE_SERCOM3 FALSE
#define SAM_SPI_USE_SERCOM3 FALSE
#define SAM_I2C_USE_SERCOM3 FALSE
 
#define SAM_SIO_USE_SERCOM4 FALSE
#define SAM_SPI_USE_SERCOM4 FALSE
#define SAM_I2C_USE_SERCOM4 FALSE
 
#define SAM_SIO_USE_SERCOM5 FALSE
#define SAM_SPI_USE_SERCOM5 FALSE
#define SAM_I2C_USE_SERCOM5 FALSE
 
#define SAM_SIO_USE_SERCOM6 FALSE
#define SAM_SPI_USE_SERCOM6 FALSE
#define SAM_I2C_USE_SERCOM6 FALSE

 
#define SAM_SIO_USE_SERCOM7 FALSE
#define SAM_SPI_USE_SERCOM7 FALSE
#define SAM_I2C_USE_SERCOM7 TRUE
 
#define SAM_SPI_USE_QSPI1 TRUE
#define SAM_WSPI_USE_QSPI1 FALSE
 
#define SAM_EFL_USE_EFL1 FALSE
 
#endif /* MCUCONF_H */
 