#ifndef SERCOM_CLK_H_
#define SERCOM_CLK_H_
#if defined(SAM_SERCOM0_GCLK_SRC_ID)
#if SAM_SERCOM0_GCLK_SRC_ID == 0
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 1
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 2
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 3
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 4
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 5
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 6
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 7
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 8
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM0_GCLK_SRC_ID == 9
#define SAM_SERCOM0_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM0_GCLK_SRC_ID*/

#if defined(SAM_SERCOM1_GCLK_SRC_ID)
#if SAM_SERCOM1_GCLK_SRC_ID == 0
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 1
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 2
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 3
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 4
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 5
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 6
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 7
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 8
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM1_GCLK_SRC_ID == 9
#define SAM_SERCOM1_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM1_GCLK_SRC_ID*/

#if defined(SAM_SERCOM2_GCLK_SRC_ID)
#if SAM_SERCOM2_GCLK_SRC_ID == 0
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 1
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK1_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 2
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK2_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 3
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK3_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 4
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK4_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 5
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK5_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 6
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK6_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 7
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK7_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 8
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK8_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM2_GCLK_SRC_ID == 9
#define SAM_SERCOM2_GCLK_GENDIV SAM_GCLK9_GENDIV
#define SAM_SERCOM2_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM2_GCLK_SRC_ID*/
 
#if defined(SAM_SERCOM3_GCLK_SRC_ID)
#if SAM_SERCOM3_GCLK_SRC_ID == 0
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK0_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 1
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK1_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 2
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK2_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 3
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK3_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 4
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK4_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 5
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK5_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 6
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK6_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 7
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK7_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 8
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK8_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM3_GCLK_SRC_ID == 9
#define SAM_SERCOM3_GCLK_GENDIV SAM_GCLK9_GENDIV
#define SAM_SERCOM3_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM3_GCLK_SRC_ID*/

#if defined(SAM_SERCOM4_GCLK_SRC_ID)
#if SAM_SERCOM4_GCLK_SRC_ID == 0
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK0_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 1
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK1_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 2
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK2_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 3
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK3_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 4
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK4_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 5
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK5_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 6
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK6_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 7
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK7_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 8
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK8_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM4_GCLK_SRC_ID == 9
#define SAM_SERCOM4_GCLK_GENDIV SAM_GCLK9_GENDIV
#define SAM_SERCOM4_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM4_GCLK_SRC_ID*/

#if defined(SAM_SERCOM5_GCLK_SRC_ID)
#if SAM_SERCOM5_GCLK_SRC_ID == 0
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK0_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 1
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK1_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 2
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK2_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 3
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK3_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 4
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK4_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 5
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK5_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 6
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK6_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 7
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK7_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 8
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK8_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM5_GCLK_SRC_ID == 9
#define SAM_SERCOM5_GCLK_GENDIV SAM_GCLK9_GENDIV
#define SAM_SERCOM5_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM5_GCLK_SRC_ID*/

#if defined(SAM_SERCOM6_GCLK_SRC_ID)
#if SAM_SERCOM6_GCLK_SRC_ID == 0
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK0_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 1
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK1_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 2
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK2_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 3
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK3_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 4
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK4_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 5
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK5_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 6
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK6_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 7
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK7_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 8
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK8_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM6_GCLK_SRC_ID == 9
#define SAM_SERCOM6_GCLK_GENDIV SAM_GCLK9_GENDIV
#define SAM_SERCOM6_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif/*SAM_SERCOM6_GCLK_SRC_ID*/

#if defined(SAM_SERCOM7_GCLK_SRC_ID)
#if SAM_SERCOM7_GCLK_SRC_ID == 0
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK0_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK0_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 1
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK1_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK1_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 2
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK2_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK2_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 3
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK3_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK3_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 4
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK4_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK4_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 5
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK5_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK5_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 6
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK6_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK6_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 7
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK7_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK7_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 8
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK8_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK8_FREQ
#elif SAM_SERCOM7_GCLK_SRC_ID == 9
#define SAM_SERCOM7_GCLK_GENDIV SAM_GCLK9_GENDIV
#define SAM_SERCOM7_GCLK_FREQ SAM_GCLK9_FREQ
#endif
#endif /*SAM_SERCOM7_GCLK_SRC_ID*/

#ifdef SAME54_MCUCONF

#define GCLK_PCHCTRL_ID_SERCOM0_CORE_Val 7
#define GCLK_PCHCTRL_ID_SERCOM1_CORE_Val 8
#define GCLK_PCHCTRL_ID_SERCOM2_CORE_Val 23
#define GCLK_PCHCTRL_ID_SERCOM3_CORE_Val 24
#define GCLK_PCHCTRL_ID_SERCOM4_CORE_Val 34
#define GCLK_PCHCTRL_ID_SERCOM5_CORE_Val 35
#define GCLK_PCHCTRL_ID_SERCOM6_CORE_Val 36
#define GCLK_PCHCTRL_ID_SERCOM7_CORE_Val 37

#endif

#endif /*SERCOM_CLK_H_*/