// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
#define SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H



#endif // SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
