##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for AT-START-F415 =====================================
	+@make --no-print-directory -f ./make/at-start-f415.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f ./make/at-start-f415.make clean
	@echo

#
##############################################################################
